// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy5gUaF_lP5-tLM01Ij9mFpOaeqLDPIc8',
    appId: '1:323153205111:web:b6fafbc001df4411dff372',
    messagingSenderId: '323153205111',
    projectId: 'iqra-student-portal',
    authDomain: 'iqra-student-portal.firebaseapp.com',
    storageBucket: 'iqra-student-portal.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3MhRMsUVJ0TP3maSH2EhY7fml65H7qkU',
    appId: '1:323153205111:android:a9c383fd8b302d26dff372',
    messagingSenderId: '323153205111',
    projectId: 'iqra-student-portal',
    storageBucket: 'iqra-student-portal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChhHyqs_5aYTnY-uYssgOljD8O_y7UAMs',
    appId: '1:323153205111:ios:3d4e75847d6bf799dff372',
    messagingSenderId: '323153205111',
    projectId: 'iqra-student-portal',
    storageBucket: 'iqra-student-portal.firebasestorage.app',
    iosBundleId: 'com.example.iqraPortal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChhHyqs_5aYTnY-uYssgOljD8O_y7UAMs',
    appId: '1:323153205111:ios:3d4e75847d6bf799dff372',
    messagingSenderId: '323153205111',
    projectId: 'iqra-student-portal',
    storageBucket: 'iqra-student-portal.firebasestorage.app',
    iosBundleId: 'com.example.iqraPortal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAy5gUaF_lP5-tLM01Ij9mFpOaeqLDPIc8',
    appId: '1:323153205111:web:6b67328283dd52d2dff372',
    messagingSenderId: '323153205111',
    projectId: 'iqra-student-portal',
    authDomain: 'iqra-student-portal.firebaseapp.com',
    storageBucket: 'iqra-student-portal.firebasestorage.app',
  );
}
