import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // This file was generated by the Terminal

// Screen Imports
import 'screens/login_screen.dart';
import 'screens/signup_screen.dart';
import 'screens/forgot_password_screen.dart';
import 'screens/dashboard_screen.dart';
import 'screens/profile_screen.dart';
import 'screens/passed_courses_screen.dart';
import 'screens/enrolled_courses_screen.dart';
import 'screens/settings_screen.dart';
import 'screens/attendance_screen.dart';
import 'screens/fee_screen.dart';
import 'screens/timetable_screen.dart';
import 'screens/notifications_screen.dart';


void main() async {
  // 1. Ensure Flutter bindings are initialized before calling async code
  WidgetsFlutterBinding.ensureInitialized();
  
  // 2. Initialize Firebase with the options for the current platform (Android/iOS/Web)
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // 3. Run the App
  runApp(const StudentDashboardApp());
}

class StudentDashboardApp extends StatelessWidget {
  const StudentDashboardApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Student UI Dashboard',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        scaffoldBackgroundColor: Colors.white,
        useMaterial3: true,
      ),
      // Define Routes for navigation
      initialRoute: '/',
      routes: {
        '/': (context) => const LoginScreen(),
        '/signup': (context) => const SignupScreen(),
        '/forgot-password': (context) => const ForgotPasswordScreen(),
        '/dashboard': (context) => const DashboardScreen(),
        '/profile': (context) => const ProfileScreen(),
        '/enrolled': (context) => const EnrolledCoursesScreen(),
        '/passed-courses': (context) => const PassedCoursesScreen(),
        '/attendance': (context) => const AttendanceScreen(),
        '/settings': (context) => const SettingsScreen(),
        '/fees': (context) => const FeeScreen(),
        '/timetable': (context) => const TimetableScreen(),
        '/notifications': (context) => const NotificationsScreen(),
      },
    );
  }
}